home/game_time.asm
home/time.asm

The last in-game year will repeat.
The uncommented block was causing problems and doesn't appear needed in the end, but further testing will tell.

Fixed #25 NoRTC overflow and bugs

---

TODO.md
home/battle.asm

Now Berries are consumed and Sash/etc isn't

Fix an inverted Berry check

---

Makefile
utils/bank_ends.py

bank_ends.py now takes a ROM filename (no extension) as an argument, so we don't need to change the script every time the ROM version is changed.

Improve bank_ends.py

---

engine/pokegear.asm

Sprite palettes were never initialized after FadeToWhite set all wUnknOBPals values to $FF

Fix issue #264: white sprites in Pokecenter town map

---

engine/move_mon.asm

Line 1700 in engine/move_mon.asm should be ld a, d not ld a, b
Register b by this point is the Pokemon's EVs, not the bit array for which stat to hyper train. That had been copied into register d though, so loading the correct register fixed this. This also properly fixed the other issue I pointed out with hyper training, so barring anything unforeseen I think it's safe to call request #272 closed.
As a side note, if it's desired to skip the hyper training loop for whatever reason, the code
`and $fc`
`jr z, .not_hyper_trained`
can be inserted at line 1701, but I didn't feel it was necessary to take up four extra bytes just to save the cycles as there's otherwise no harm in going through the loop anyway.

Fix #272 - perfect DV stat calcs

---

data/battle_tower/parties.asm

Battle Tower parties will not load properly since the BattleTowerPokemon2 label is misplaced, and that label is used to determine the size of the Battle Tower Pokemon set. Putting this where it needs to be fixes that issue.

fix Battle Tower glitchy parties

---

engine/battle/effect_commands.asm
engine/selectmenu.asm

Substitutes will always break after one hit because HP is stored as big-endian but treated (for substitutes) as little-endian. This code fixes that. Arguably, it's debatable if we even need two bytes for substitute, given the maximum substitute HP possible is 178 (from Blissey's max HP of 714), which can be stored in one byte, but since HP is otherwise stored as two bytes I'll just leave it alone. Important to note is that making that change would require getting rid of these +1 I just added as they'll lead to trouble.
Also, there's an unnecessary call to DelayFrame I left behind from the select menu fix, so this will just clean that up.

fix substitute issue/remove unnecessary frame delay

---

Makefile
engine/battle/core.asm
engine/evolve.asm
engine/item_effects.asm

Fixes #287 - this one was entirely my bad, when I removed a ton of code from PursuitSwitch to remove the reliance on wLastPlayerMon, I didn't realize that I'd unwittingly removed a bit of code that properly sets which Pokemon we switch into. Loading wCurBattleMon back into wCurPartyMon (since wCurBattleMon is exclusive to the player mon) before calling PlayerSwitch would seem to fix that problem.
Fixes #277 and refactors item_effects.asm - item_effects.asm honestly needed to be cleaned up a bit, and based on my testing the modifications I've made have preserved the exact functionality of the original file, just with a bit more efficiency. The issue with crashing upon evolution is better resolved just by setting wCurForm during the evolution script, since it's only otherwise needed for …

set of bug fixes, including switch/predict bug

---

engine/battle/core.asm
engine/evolve.asm
engine/item_effects.asm
engine/startmenu.asm

Fixes #250 and fixes #260
Both these issues have the same source:
- have a Pokemon trying to learn a move in the overworld
- open up that Pokemon's forget a move screen
- close that screen
You'll be back in the party menu, and if the Pokemon isn't 6th in your party you'll enter a glitchy state. This is because wCurPartyMon and wCurPartySpecies aren't preserved after redrawing the party menu, so they end up having the values correlating to the last Pokemon in your party. Since that's never reset, it'll lead to problems like the two issues listed above. Preserving those variables solves those problems and also solves an issue where Yanma will not evolve if it learns Ancient Power in the overworld via leveling up.
Also has some minor bugfixes - namely, all HP items restore full health due to …

preserve wCurPartyMon/wCurPartySpecies variables while learning move, and other fixes

---

gfx/items.asm
main.asm

Fixes #293 - this wasn't specific to faithful, the issue is that all pointers to NoItemIcon for items past index $EA (including $FF) were removed, so arbitrary code was being executed upon decompressing that sprite. There was a few ways I could've done this but for now I decided to just have it where $FF is checked for in wCurItem, and if it's found then the item icon at pointer $00 is used, which is NoItemIcon. Note that any glitch items $EB to $FE will still crash the game upon opening their icon, so if that's undesirable then use the following code:
`    ld a, [wCurItem]`
`    cp MIRAGE_MAIL + 1`
`    jr c, .has_icon`
`    xor a`
`.has_icon`
in place of the code I used. Note that this will cease to work if an item has an index higher than Mirage Mail ($EA as of this writing). This …

fix game crash on opening bag

---

engine/switch_items.asm

Fixes #298 - the reason the sort crashes is because Cancel ($FF) gets its sort item index (arbitrary value) before any checks for whether $FF is selected takes place. Ensuring that GetSortingItemIndex returns a = $FF when Cancel comes up means the sort can exit successfully. I presume this came about due to item_constants.asm no longer making constants for unused indexes, so we'll have to keep an eye out for similar issues going forward.

fix game hang on sorting items by name

---

constants/battle_constants.asm
engine/battle/effect_commands.asm

Fixes #266 - game would (sometimes) crash when using Roar on a flying/digging mon because text wasn't properly loading text when wAttackMissed = 1. Also, the constant ATKFAIL_CUSTOM should actually have a value of zero, not six to match up with the jump table set up. I know there's a TODO to use it more often and I believe it is now correctly set up. I do think it should use a more generic name, but I can't immediately think of one, sorry.

fix crash on using FailText_CheckOpponentProtect

---

engine/events/itemball.asm
home.asm

Fixes #301 
Not really much to say. I did delete an unnecessary `ld a, [wNamedObjectTypeBuffer]` that gamefreak was kind enough to leave for us, though. I have to wonder if it might be a good idea to refactor how key item names are fetched by having the `inc a` simply occur in `GetKeyItemName` instead of all these disparate areas, but I'll leave that up to you since I may not be taking everything into account here.

fix off-by-one error for key item ball

---

data/pokemon/evos_attacks.asm
engine/map_objects.asm

Fixes #283 - this wasn't a script issue, it was an engine issue regarding an interaction between movement speed and duration from StepVectors and the Y-offset table from UpdateJumpPosition. Structurally, a jump is two parts - .Jump and .Land, both of which have the same max number of frames for each movement type. A slow movement takes 32 frames, so .Jump = 32 frames and .Land = 32 frames for a total of 64 frames per jump. Speed, as it relates to jumps, determines the rate at which the Y-offset changes for a sprite per frame. It's calculated as n/2 updates per frame. A slow jump has a speed of 1, so the Y-offset will update once every two frames. UpdateJumpPosition contains a table of 16 Y-offsets that a jump can take in total from start to finish. For a fast jump (2 updates per frame) it …

fix slow_jump_step_* movements

---

engine/events/happiness_egg.asm
engine/item_effects.asm

Previous commit had EV-lowering berries fail if the EV was already zero before use, but in actuality it should only fail if EV is already zero _and_ happiness is already maxed. This PR fixes that. ~~No other functions that called `ChangeHappiness` care about whatever value returns in `a` as far as I can tell, though I do want you to be aware that `a` is now always 0 upon return regardless of success.~~

fix when EV-lowering berries fail

---

contents/bank_ends.txt
engine/battle/ai/switch.asm
engine/battle/core.asm
engine/battle/effect_commands.asm
roms.md5

Fixes #439 - `wTypeModifier` simply was not reset properly upon switching in a new Pokemon, only being xor'd by `SendOutPlayerMon` and untouched when an opponent sent in a new Pokemon. I basically just made sure $10 was loaded into `wTypeModifier` in `SendInUserPkmn` which handles both player and opponent Pokemon anyway, and subsequently removed the load in `SendOutPlayerMon`. Also, `BattleCommand_resettypematchup` would improperly set `wTypeMatchup` to $10 instead of resetting `wTypeModifier` so I fixed that, though I'm not sure if that ever caused a problem of its own.
Fixes #466 - It's not clear to me if this ties in with fainting from burning at all, but in `AICheckMatchupForEnemyMon` basically the opponent AI would improperly score all potential switches to $0 or $1, depending on …

fix toxic spikes and glitched opponent switch-out

---

contents/bank_ends.txt
engine/battle/move_effects/attract.asm
engine/events/overworld.asm
engine/movie/init_hof_credits.asm
engine/pokedex/pokedex.asm
engine/pokemon/bills_pc.asm
engine/pokemon/breeding.asm
roms.md5

**Addresses (maybe part of?) #457** - In `InitDisplayForLeafCredit` the game attempts to fill `wBGPals1` and `wOBPals1` with white palettes. However, there is never a wram bank switch to the correct bank first, so instead of overwriting those addresses in bank 5 it overwrites those addresses in bank 1 instead. This causes it to overwrite the first byte of `wPlayerID`, and when the player attempts to save the game will assume the player is playing on a new save file due to this new TID and will wipe the old save info if the player picks yes. _Note that this bug also exists in vanilla Crystal for Red's endgame credits._ However, since `wBGPals1` and `wOBPals1` have different physical locations in vanilla, they're just overwriting some temporary buffers. All that said, since the code did …

a few bug fixes, including a save "corruption" and a crash

---

contents/bank_ends.txt
data/moves/effects.asm
engine/battle/abilities.asm
engine/battle/effect_commands.asm
engine/battle/move_effects/pursuit.asm
engine/menus/intro_menu.asm
ram/wramx.asm
roms.md5

**Fixes arbitrary post-battle jump with egg in party -** Having an egg in the party would cause `RunPostBattleAbilities` to continue its party checking loop with a `push bc` without reaching its subsequent `pop bc`, leading to an arbitrary jump and a possible game crash.
**Implements unused Pursuit animation -** I said earlier in Discord that Beat Up is the most interesting move in Gen 2, but I changed my mind, it's definitely Pursuit. At least Beat Up works in Gen 4. Did you know that Pursuit (in most cases, but mysteriously not all) doesn't do anything at all in spaceworld? Like, it doesn't even reduce its own PP upon use? At least Beat Up has the excuse of being a last minute implementation of an unusual mechanic. Anyway, to implement this I just moved the Pursuit damage doubling stuff …

fix arbitrary jump with egg in party and implement unused pursuit anim

---

INSTALL.md
tools/collision_asm2bin.sh

MacOSX doesnt come with md5sum (it has a pre-installed md5 utility but it hasnt -c option required for `make compare`)
Since md5sum is required to `make` and `make compare`, this PR add instructions to install it on OSX.
Moreover the script tools/collision_asm2bin.sh uses `tail` and `head` with negative -c param, which is not supported by embeded head and tail binaries, causing buggy/missing collisions ig.
`head: illegal byte count -- -8` are visible in `make` logs.
ref:
https://unix.stackexchange.com/questions/169079/negative-arguments-to-head-tail
https://www.garron.me/en/bits/how-to-md5sum-mac-os-x.html
https://raamdev.com/2008/howto-install-md5sum-sha1sum-on-mac-os-x/

Allowing Toolchain to work properly on OSX

---

tools/collision_asm2bin.sh

Busybox mktemp requires a template with a fixed number of X. This commit
allows Polished Crystal to be compiled within busybox environments, such
as w64devkit on Windows.
Also tested working with Debian.
Signed-off-by: Mahyar Koshkouei <mk@deltabeard.com>

Add support for compiling with busybox mktemp

---

engine/battle/effect_commands.asm

When using a two-turn move like Fly or Dig, the 'used move text' (`[Pokémon] used [move]!`) disappears immediately after it's fully displayed - when the charging animation starts. When text speed is set to instant, it flashes on screen for a split second. 
With this change, the 'used move text' will continue to be on screen during the animation.

Fix 'used move text' when charging a two-turn move

---

engine/battle/effect_commands.asm
engine/battle/move_effects/future_sight.asm

1. If a Pokémon used Future Sight, the text `[Pokémon] used Future Sight!` disappears immediately after it's fully shown, being replaced with `[Pokémon] foresaw an attack!`.
2. If a Pokémon uses a move but there was not target anymore (for example, after that target selfdestructed), the text `[Pokémon] used [move]!` disappears immediately after being shown, being replaces with `But it failed!`.
In both cases, the solution was to add a delay.

Fix two battle texts disappearing too fast

---

engine/battle/ai/redundant.asm

In certain situations, trainers keep spamming Destiny Bond - even when they already used it the previous turn and therefore is a guaranteed fail. I got this situation when fighting with a Poliwrath against trainer Vivian in Rock Tunnel. 
I added the move Destiny Bond to the redundancy checks, to keep trainers from using it if the target already has the Destiny Bond sub status.

Add redundancy check for Destiny Bond

---

data/phone/text/bill.asm

A tiny PR that fixes having to press A twice at the end of Bill's phone call after gaining the second badge in Kanto. Now it behaves like other phone calls.

Fix having to press A twice to end Bill's call

---

engine/battle/effect_commands.asm

1. The animation that is shown when a Pokémon hits itself in confusion did not show. It seems this was accidentally removed in [this commit](https://github.com/Rangi42/polishedcrystal/commit/0c4a1e04e6900f9fdeac9f695fcb229d5e1ec45c#diff-88dbff1eb3920f69b17a3d5f613643e1a41096514706bc09f449e4aa637f20e4).
2. If the second turn of Dig/Fly fails (for example, when the Pokémon hits itself in confusion) the Pokémon's sprite stayed invisible. This was reported in #665. 
Resolves #665.

Fix two bugs in battle animations

---

maps/ElmsLab.asm

After beating Prof. Elm at his lab, Lyra will come in to announce her gym challenge. However, if you talked to Prof. Elm from above, she will phase right into professor Elm. Also, after her announcement, the player will not be facing the correct direction in 2 out of the 3 scenarios.
This PR fixes both these issues.

Fix scripting around Lyra's announcement of her Gym challenge

---

maps/VermilionCity.asm

After the first encounter with Lawrence in Kanto, he disappears on the spot. This looks a bit weird since there's a huge pier below. This PR makes him walk down that pier out of sight.

Improve Lawrence's leaving animation

---

maps/CeruleanCity.asm
maps/Route24.asm

- Fix for incorrect `Itemfinder` casing on a sign
- Fix flashing message boxes during interaction with cool trainer and her Slowbro
- Fix some issues with bridge overhead/underfoot triggering where the player's sprite would be cut-off on certain tiles when entering from Cerulean City and where event triggering could be circumvented by flying

Fix some issues in & around Cerulean City

---

data/text/common.asm

Hi, while testing 9bit I noticed that the text at this position auto-scrolled by and no Pokémon cry was audible.
Judging by pokecrystal, this should be a ```text_end``` ?
https://github.com/pret/pokecrystal/blob/master/data/text/common_2.asm#L1544

Fix Sylveon cry in intro

---

engine/battle/core.asm

This is the same bug that happened in #519. This PR is to resolve this. The issue occurs because `LinkBattleSendReceiveAction` contains a call to `PlaceWaitingText`, however the Tilemap isn't being properly copied to temp and back.

Fix link "Waiting..." textbox getting stuck.

---

engine/overworld/scripting.asm

When receiving a key item, the player could (accidentally) instantly close the 'received item' text. With this PR, the SFX has to be played before the text can be closed. This is now consistent with receiving a TM/HM.

Wait for sound effect on receiving key item

---

maps/MrPokemonsHouse.asm

When receiving the Odd Souvenir from Prof. Elm, he says it was given to him by Mr. Pokémon.
Since I didn't know what the Odd Souvenir was for, I went straight to him, but there was no dialogue about the souvenir. I thought it'd be nice for him to tell something about it, so I added dialogue explaining how the Odd Souvenir works (well, kind of).

Add Odd Souvenir dialogue to Mr. Pokémon

---

engine/events/overcast.asm

This prevents the jarring palette change when transitioning from Goldenrod City to Magnet Tunnel West during the Rocket Takeover. [See here](https://discord.com/channels/332698009060114434/332698009060114434/1010557829528158338)

Add Magnet Tunnel West to overcast checks

---

engine/events/overworld.asm

~Addresses [pret/pokecrystal#994](https://github.com/pret/pokecrystal/issues/994)~
Addresses ["You can fish on top of NPCs"](https://pret.github.io/pokecrystal/bugs_and_glitches.html#you-can-fish-on-top-of-npcs) from pokecrystal's bug docs

add check for facing sprite when fishing

---

data/text/common.asm
engine/events/name_rater.asm
engine/items/item_effects.asm

...Unless the traded-pokémon-treat-you-as-OT option is set.

Disable changing the ball of a traded pokémon

---

maps/Route22Past.asm

Lyra's dialogue regarding Celebi is a bit confusing. The original HGSS event has clearer text. This pull request adds some of that text.
The pull request adds **additional dialogue** for Lyra, extracted from the HGSS event:
```
Is that... am I looking at... Celebi?
That explains it!
```
This text happens right before the text `"Celebi must have used its power to [...]"`, in Route 22.
The pull request also **slightly modifies Lyra's movement** in the event to make it clearer that she's seeing Celebi for the first time. This movement resembles more the movement she has in the HGSS event.
The first time I played through the Celebi event, the way Lyra talked about Celebi and the legend of the shrine confused me. I had not played the original HGSS event before, but after watching a video …

Celebi event, make Lyra's text related to Celebi more clear

---

engine/pc/bills_pc.asm

`CurBoxFullCheck:` correctly returns the `Z` flag when the decremented `wTempMonBox` == `wCurBox`, however it also returns the current box value in register `a`. Thus, `Special_CurBoxFullCheck:` incorrectly reports Non-Full box numbers > 1 as ( `!=` or `nonzero`). This can be fixed by simply checking the zero flag and clearing register `a` before loading into `hScriptVar`.
I confirmed the bug as reported occurs when the player receives something like an egg with a full party, and current box is greater than box 1. The reported "Wise Glasses is full." and "Pecha Berry is full." is due to how `CurBoxFullCheck:` never runs `GetCurBoxName` as it **correctly** returns prior. The issue is cause by the mapscript incorrectly executing `farwritetext _CurBoxFullText` after an incorrect return value …

`Special_CurBoxFullCheck` incorrectly returns nonzero for Non-Full box numbers > 1

---

constants/map_object_constants.asm
engine/overworld/map_object_action.asm
engine/overworld/map_objects.asm
engine/overworld/movement.asm
engine/overworld/npc_movement.asm
engine/overworld/player_movement.asm
engine/overworld/player_object.asm
engine/overworld/stone_table.asm
home/map_objects.asm
home/stone_queue.asm
home/trainers.asm

Sync's the `OBJECT_` constant names with pret. I used REGEX to do this, so if you prefer your current constant names, feel free to close this. I was trying to read through some polished code, and the OBJECT names conflicting with pret's was throwing me off.. I'm sure it would for others if you plan for others to use polished as a base. 
I verified the sha1 of the rom is not changed with this PR.

Sync `OBJECT_` constant names with pret

---

engine/events/overworld.asm

Resolve issue where ExtSpecies/Forms were not working correctly while fishing. Need to use `wWildMonForm` instead of `wCurForm` in `FishFunction:` to bypass `wCurForm` from being overwritten later by `GenerateWildForm:`
Resolves Discord Bug Reports: 
https://discord.com/channels/332698009060114434/933019563535253534/1054681881540567091
https://discord.com/channels/332698009060114434/933019563535253534/1054685241157095454

Fix Fish WildMon Forms

---

engine/gfx/cgb_layouts.asm
engine/gfx/color.asm
engine/gfx/mon_icons.asm
engine/pokemon/move_mon.asm

I've only managed to partially fix this so far...
The issue mainly was:
If a party is "full", `LoadNamingScreenMonMini:` would call `GetPartyParamLocationAndValue:` and use `wPartyMon1Form` instead of `wTempMonForm`. Thus, if an Egg Or a pokemon with a Form was in the first slot, and the player catches a pokemon.. The naming screen will either show an Egg icon/text or a glitched icon.
This is only a partial fix so far... Although the correct icon/text now loads.. the palette is still wrong. I haven't been able to figure that out yet...

Full Party Naming Screen Issues

---

engine/pokemon/move_mon.asm

`RetrieveBreedmon` reads in old/garbage data for `wCurForm`. This is caused by reading the "LastPartyMon"'s Form byte *BEFORE* we had a chance to copy the `BREEDMON_STRUCT` to the "LastPartyMon" slot.
Having garbage data in `wCurForm` causes `GetBaseData` to produce garbage data, thus causing the occasional breedmon Div by 0 error in `CalcExpAtLevel:`. I predict it is also highly likely that his problem causes the other bug reports where occasionally a mon instantly jumps to level 100 from the daycare.
Please see below for bug reports.
https://discord.com/channels/332698009060114434/933019563535253534/1061069088123793499
https://discord.com/channels/332698009060114434/332698384987193354/1067665669753151518
https://discord.com/channels/332698009060114434/332698384987193354/10678023478514852 …

Resolve `RetrieveBreedmon` reading garbage data for `wCurForm`

---

engine/overworld/events.asm

As the title explains, this fixes a recent break with wild encounters in caves and dungeons.

Fix `CAVE`/`DUNGEON` wild encounters

---

home/copy.asm
home/decompress.asm
home/joypad.asm
home/video.asm
ram/hram.asm

Stuff i've been working on, mostly against base crystal, but would like to see used somewhere; Much of my changes don't apply to polished but these few do
And a random fix to WaitPressAorB, so it doesn't busy the cpu when stat changes on level up are shown
UpdateBGMapBuffer now depends on  wBGMapBuffer and wBGMapPalBuffer not crossing a 256 byte boundary, they don't but not sure how i should assert for that
Hopefully Decompress is readable enough. Subroutines are in an... eclectic order, mostly from rearranging whenever they were out of jr range, and the code quite dense, some of which is unavoidable

Some optimization

---

engine/gfx/sprite_palettes.asm

Doesn't seem to affect anything.. but should be corrected just in case.

Fix CopySpritePal wrong order pops

---

data/maps/setup_scripts.asm
engine/battle/battle_transition.asm
engine/events/overworld.asm
engine/gfx/color.asm
engine/gfx/dynamic_pals.asm
engine/menus/start_menu.asm
home/map.asm
home/menu.asm
home/sprite_updates.asm

* No longer run Dynamic Pal in `LoadMapPals`
* Don't update `OBJECT_PALETTE` during the first dyn pal pass.
* Better Menu exit hook (Doesn't corrupt BG)
* Ensure the correct Wram bank is loaded.
* Preserve more registers, just in case.
* Re-fix Battle Transitions
* Re-fix sprites appearing before warp is complete
* Fix sprite problems when activating surf (Menu problem).
* Verified pals updating correctly when crossing map connections with different map conditions (Example: Overcast)

Some Dynamic Pal Improvements

---

engine/overworld/scripting.asm

This should fix problems with `follow`, `follownotexact`, `checkmapscene`, and `setmapscene`.
This was broke in #808 and the fix identified by @ariscop

Fix `GetScriptWordBC` endianness

---

data/maps/setup_script_pointers.asm
data/maps/setup_scripts.asm
engine/gfx/dynamic_pals.asm

As the title suggests.. this allows dynamic pal system to only write pals to `wOBPals1` and not `wOBPals2` during warps/doors/ect.. allowing compatibility with the pal fading. This way the npc's/objects fade in properly and smoothly from white, and don't "pop in" early.

Fix DynPal compat with pal fade

---

home/decompress.asm
tools/lz/dpcomp.c
tools/lz/output.c
tools/lz/proto.h
tools/lz/uncomp.c
tools/lz/util.c

Reducing the max length costs a few bytes due to split commands, but growing the minimum size also saves a few
Net result is a smaller faster decompress and a slight reduction in rom usage

Compressor changes

---

data/events/special_pointers.asm
engine/events/field_moves.asm
engine/events/sacred_ash.asm
engine/tilesets/timeofday_pals.asm
home/sprite_updates.asm
maps/BluesHouse1F.asm
maps/CianwoodCityPhotoStudio.asm
maps/CinnabarLab.asm
maps/GiovannisCave.asm
maps/IlexForest.asm
maps/OlivineLighthouse6F.asm
maps/Route22Past.asm
maps/TeamRocketBaseB1F.asm
maps/TeamRocketBaseB2F.asm
maps/WarehouseEntrance.asm

Fixes objects going white when using FLASH in darkness. This also fixes `FadeInPalettes` when used in various map scripts.

DynPal Fix Flash in Darkness and `FadeInPalettes`

---

audio/drumkits.asm
audio/engine.asm
audio/sfx.asm
audio/sfx_pointers.asm

```
Before: ROMX: 2003678 bytes used / 11554 free in 123 banks
After:  ROMX: 2003384 bytes used / 11848 free in 123 banks
```

Audio space saving

---

engine/menus/main_menu.asm
engine/rtc/rtc.asm
home/game_time.asm
home/time.asm
ram/hram.asm
ram/wramx.asm

Ends up being pretty much equivalent, uses a few less rom0 bytes and 5 less hram bytes
Reduces the delta with the no-rtc build
UpdateTime already assumed rSVBK == 1 but only on no-RTC, so it's possible bugs in that build would be exposed to rtc-enabled builds

Move hRTC* to wram

---

audio/engine.asm
macros/scripts/audio.asm

```
Before: ROMX: 2004054 bytes used / 11178 free in 123 banks
After:  ROMX: 2002147 bytes used / 13085 free in 123 banks
+1907 bytes
```
Changes stereo panning and duty cycle to avoid an argument byte, and a few other things
Music source compatible, with the exception of `stereo_panning FALSE, FALSE` which is no longer valid

Compacting music commands

---

audio/engine.asm
audio/music/swsh/gymleaderbattle.asm
constants/audio_constants.asm
engine/overworld/player_movement.asm
home/audio.asm
macros/ram.asm
macros/scripts/audio.asm
ram/wram0.asm

Removes dead code, unused variables, and elides many hl loads
Commands like new_song and restart_channel are currently unused and were not tested as a result. it may make sense to remove them
238 fewer rom bytes and 116 less wram0

Sound engine optimization

---

audio/engine.asm
audio/music_player.asm
home/lcd.asm
layout.link
ram/wram0.asm

Memory used by the audio engine moved into its section
As a side effect, settings are preserved when re-entering the
music player
+2 trivial patches

Move music player ram to Misc 480

---

engine/gfx/sprite_palettes.asm

Can't believe this didn't cause more problems. Fixes the pokeball's using wrong pals when in darkness:

DynPal: Fix darkness/overcast pal problems

---

audio/cries.asm
audio/engine.asm
audio/music/b2w2/marinetube.asm
audio/music/go/gymbattle.asm
audio/music/go/wildbattle.asm
audio/music/hgss/ceruleancity.asm
audio/music/stadium/mewtwobattle.asm
audio/music/undertale/megalovania.asm
audio/music_player.asm
constants/audio_constants.asm
engine/menus/options_menu.asm
macros/ram.asm
ram/wram0.asm

Removes all stereo-dependant branches, engine is essentially stereo only, with stereo/mono mixing handled when writing rNR51. The options menu no longer restarts the music as the change applies instantly
Fixes #837 but i'm not entirely sure the fix is correct

Audio engine fixes

---

engine/games/unown_puzzle.asm
home/sprite_anims.asm
home/video.asm
layout.link
ram/wram0.asm

Mostly removes unused constraints in layout.link
Misc 480/1326 are both 4 bit aligned, nothing seems to depend on that fact anymore (wMisc likely used to) but it cost nothing to preserve that
The only alignment sensitive code i found dealt with wBGMapBuffer, for which asserts are provided

Wram housekeeping

---

engine/battle/effect_commands.asm

Created a call just for Throat Spray to account for both damaging and non damaging sound moves. Uses wAttackMissed to see if the attack hit.

Throat Spray now works for both damaging and non-damaging moves.

---

data/moves/sound_moves.asm

Heal Bell, as a sound based move in the mainline games, should be able to trigger throat spray's +1 SpA buff when used by a pokemon holding the item. As heal bell was not currently in the db for sound moves, it currently does not do so. This PR aims to fix that.
Possible Issues:
-This might interact weirdly if a pokemon with soundproof uses heal bell? The vanilla games already have a somewhat weird soundproof+heal bell interaction anyways

Allow Heal Bell to Trigger Throat Spray Buff

---

engine/pokemon/mon_menu.asm

Added moved the call to SetPalette after LoadPartyMenuGFX but before InitPartyMenuGFX to prevent a frame of incorrect palette after swapping mons.

Prevent frame of incorrect palette on mon swap in party

---

engine/events/specials.asm
engine/pc/bills_pc_ui.asm
maps/GoldenrodGameCorner.asm

Went through some of the issues list. Added Piers rematch to the E4 reset, adjusted some file structure of GoldenrodGameCorner to match CeladonGameCorner (was doing this when looking into Issue #656, which I cannot recreate at all, I think that one can be closed), and the larger one is adding the functionality to move the cursor to the currently showed pokemon on the stats screen when scrolling through the box/party in the PC.
Piers Rematch: https://github.com/Rangi42/polishedcrystal/issues/814
GameCorner Coin Refund: (cannot recreate this, I don't think this can happen anymore if it did) https://github.com/Rangi42/polishedcrystal/issues/656
Cursor not moving after statscreen: https://github.com/Rangi42/polishedcrystal/issues/624

Various bug fixes

---

README.md

This hotfix applies the tag update (eefb276) to the link in README. There have been some questions about how to get to the page these days, and the latest one added that the link was 404, which is a good catch and explains why.

Fix the link in readme

---

constants/pokemon_constants.asm
data/pokemon/base_stats/mr__rime.asm
data/pokemon/egg_move_pointers.asm
data/pokemon/evos_attacks.asm

Noticed a couple things while writing data scraping utilities that I thought I'd fix and PR.
* Most notable, Delibird's learnset doesn't actually have a terminator and falls through overlapping Mantine's below. Technically this overlap could be intentionally utilized to save a magical 100 or so bytes, but this seems to just be an error
* `pokemon_constants` refers to a missing file `idle_pointers.asm`, which seems to have been renamed to `extra_pointers.asm`. I'm not clear if the list in `pokemon_constants` is otherwise complete, but nothing else matches the substring `assert_table_length NUM_SPECIES` so I assume it's fine
* Mr. Rime has a hardcoded 4 instead of a `HATCH_MEDIUM_SLOW` constant. It seems to be the only mon that did this
* While a lot of lookup tables based on pokemon …

Add missing learnset terminator for Delibird and clean up other minor issues

---

home/pokemon.asm

The event in Elm's Lab doesn't trigger if you hatch a female Togepi. In the function that handles setting that event, gender is never reset, so it may be the reason why it glitches out. Reseting the gender flag fixes the issue.

Togepi egg event fix

---

home/palettes.asm
maps/FastShipCabins_SE_SSE_CaptainsCabin.asm

This is still not quite perfect yet... but its better. The main issue here has to do with the fact that this scene has the player move through the void from one room to another while the pals a "faded out". This triggers the dynpal system when new objects are loaded. 
Also it seems that `Special_FadeBlackQuickly` was setting the BG pals to grey.. and all OBJ pals to grey except for OBJ0 which was being set to Black. Since the player is typically OBJ0... They show up as black on a grey background in this scene.... 
So I made a `FadeToBlackQuickly` for now... Which just fades ALL pals to black.. and then we reload them before fading back in.
The fade in is still a little gittery.. i'll look into this a bit more. I'll also take suggestions.

Fix for FastShip CaptainsCabin scene transition

---

data/pokemon/evos_attacks.asm

Changes to the order of evo_data listings for Koffing and Mime Jr. to allow both to evolve into their regional forms at or past the level they would otherwise evolve into their regular forms.

Fix evos_attacks.asm Evo_Data Orders

---

data/pokemon/base_stats/corsola_galarian.asm
data/pokemon/base_stats/cursola.asm

Changes both galarian corsola and cursola to Ghost/Rock in unfaithful build.

add secondary rock typing to galarian corsola line

---

maps/CliffEdgeGate.asm
maps/GoldenrodDeptStore4F.asm

Since the Linking Cord replaced EV-Based Evolutions, this pull request edits GoldenrodDeptStore4F.asm and CliffEdgeGate.asm to reflect this change in the dialogue.

[9-Bit] Removes Outdated EV Evolution Text

---

home/battle.asm

Lagging tail was missing an `inc d` like `.set_priority` has to properly do the +1/-1 based on battle turn, instead doing +0/-2, which meant lagging tail did not work for enemy trainers. Further, a player with lagging tail and an enemy with quick claw could create -3, which is not considered part of the valid range for `d` in this routine. `.set_priority` was changed to be used for both increasing and decreasing priority called from the nicely named `.go_first` and `.go_last` labels.
I initially discovered this when implementing the Stall ability, the `.go_first` `.go_last` labels make that slightly more reasonable, and it makes the code here more readable, so I decided to bundle it with the lagging tail fix.

Fix lagging tail, quick claw, and quick draw

---

engine/battle/battle_transition.asm
engine/battle/sliding_intro.asm
engine/battle_anims/anim_commands.asm
engine/battle_anims/bg_effects.asm
engine/battle_anims/functions.asm
engine/events/magnet_train.asm
engine/events/map_name_sign.asm
engine/link/link.asm
engine/menus/intro_menu.asm
engine/movie/credits.asm
engine/movie/intro.asm
engine/movie/title.asm
engine/overworld/init_map.asm
home/lcd.asm
home/serial.asm
home/vblank.asm

The idea is to only enable LCD_STAT when its actually needed. This can be found by enabling it whenever `hLCDCPointer` has a non-zero value... and disabling it when it is set back to zero.

Only enable LCD_STAT when needed.

---

data/moves/animations.asm

As discovered by a few individuals and finally confirmed while working on CSE with SourApple, 8bitZeta, and Monstarules. The vanilla pokecrystal tackle animation runs into a sprite limit due to an unneeded second row being copied from the enemy's "feet" to sprites. Pokemon Gold and Silver only copied a single row, and didn't have this problem. Unsure why Crystal decided to do this.
See the below as an example of what this looks like before this fix:

Bugfix: Tackle animation sprite limit

---

maps/Route36NationalParkGate.asm

>After the Bug Catching Contest is over due to the player opting to end it early, the BG fades in from black, but the NPC sprites do not, meaning a second or two where the NPCs are all standing on a black void before the BG fades in
This PR resolves the above. Related to #905

Fix Bug Catching Contest End Early FadeInPalettes

---

engine/battle/trainer_huds.asm
engine/gfx/cgb_layouts.asm

- Shift Nuzlocke icon left a square.
- Don't skip the caught icon is the Nuzlocke icon is showing
We'd probably have to re-arrange other things if we don't want to shift this far left. See how it looks now below.
It being shifted left doesn't look bad when the caught icon is *also* showing.. but when its just the nuzlocke icon, it can look a little off.. I could adjust the code to only shift the nuzlocke icon if the caught icon *isn't* showing. Let me know what you think.

Shift Nuzlocke Icon Left, Don't skip caught icon

---

data/maps/setup_script_pointers.asm
data/maps/setup_scripts.asm
engine/overworld/map_objects.asm

Player will no longer be standing "above" the grass when exiting the grotto into grass. If there are other grottos that may exit onto grass, you simply need to call `UpdatePlayerTallGrassFlags` from the maps OBJECT callback.
Reference #905

Fix grotto exit on route36 player standing on grass

---

engine/overworld/player_movement.asm

Acts similar to the Gen I / Gen III remake behavior on Cycling Road. Holding B will brake the bike while going downhill on Cycling Road.

Allow holding B on cycling road to brake the bike

---

engine/pokemon/mon_menu.asm

I opened this as a PR mainly because I don't fully understand why the this fixes the problem.. but it does fix it.  
This was fixed in CSE.. see the issue there:  
reference fellowship-of-the-roms/CrystalShireEngine#27  
Furthermore, this is _probably_ also related to Darsh' comment here: [https://github.com/Rangi42/polishedcrystal/issues/857#issuecomment-1826199307](https://github.com/Rangi42/polishedcrystal/issues/857#issuecomment-1826199307)  
\>I do think there's something wrong with the sound engine. A Pokemon's cry in the status screen isn't always going to have consistent volume (Voltorb is a good example of this). Not clear what's causing the issue.

Fix Stats screen at max volume

---

engine/pokemon/party_menu.asm

Addresses enhancement issue: #988 
Adds same logic as [KnowsMove subroutine](https://github.com/Rangi42/polishedcrystal/blob/9bit/engine/items/tmhm2.asm#L585-L604) to the party menu's `PlacePartyMonTMHMCompatibility` subroutine to check whether a Pokemon already knows a move before placing the "able" or "not able" text next to the Pokemon's name. 
- This may not be the cleanest implementation! Let me know and I'll try and address.
- Is there any other place we'll need to implement this? I didn't see anywhere else while I was looking around the code.
- I needed to manually to manually increment the `wCurPartyMon` variable, or else the knows move logic kept comparing against the last Pokemon in the party. Is this necessary / is there a better way to do this?
- I didn't call the `KnowsMove` …

Add "Learned" to teach TM/HM screen

---

data/pokemon/evos_attacks.asm
data/pokemon/evos_attacks_pointers.asm

Another difference I noticed while parsing for the wiki. Bloodmoon Ursaluna's moves weren't getting parsed. For some reason it was the only Pokemon that used `EvoAttacks` instead of the plural `EvosAttacks`. I believe this should only be cosmetic but let me know if it's not.

Change UrsalunaBloodmoonEvoAttacks to UrsalunaBloodmoonEvosAttacks

---

data/pokemon/base_stats/goldeen.asm
data/pokemon/base_stats/seaking.asm
data/pokemon/base_stats/smoochum.asm

Only Goldeen, Seaking, and Smoochum were commented differently for some reason. This is just a cosmetic difference I noticed while parsing the files for the wiki.

Rename "items" comment to "held items" in base stats files

---

constants/tileset_constants.asm
data/tilesets.asm
home/map.asm
ram/wramx.asm

This splits the tileset graphics into their own sections.... This was needed because the Johto tileset section was nearly 0x4000 bytes large preventing us from adding anything or even modifying anything that might de-optimize the lz compression.

Split tileset graphics into their own sections

---

ram/wram0.asm

`Misc 1326` just happened to be 16 byte aligned. Ran into this in another project, best to future proof.

Fix summary screen alignment which was correct on accident

---

engine/overworld/player_step.asm
home/map.asm

We check if the player is walking onto a `COLL_COAST_SAND` cell, or if we are leaving a `COLL_COAST_SAND` cell. If so, we don't reload the walked tiles. This avoids deleting the footprints.
Resolves #1041

Don't reload walked tiles if walking onto/leaving `COLL_COAST_SAND`

---

engine/pokemon/evolve.asm

Levelup moves lost a preserved flag in the transition to method calls, this does nothing fancy and just pushes and pops the flags. There's probably a faster solution but I just didn't think.
Evolution moves were moved to a different bank so the current routine was reading garbage, this fixes that with far byte reads.
Tested with various mons.

[10bit] Fix levelup moves and evolution moves

---

constants/misc_constants.asm
engine/battle/core.asm
engine/events/magikarp.asm
engine/menus/intro_menu.asm

Making this pull request purely for posterity, as it could deserve a save patch. This would close #1131 
Really, there are three issues this is resolving:
1. When starting a new save file, the game initially stores the record Magikarp's length as $0306. This is a vestige from when the Polished codebase was in imperial units and the intended length was 3'6". However, the codebase is now in metric units, but the Magikarp length code hasn't been updated. Effectively this means the initial longest Magikarp is a pathetic 776mm, or about 2'6". The game now initializes to the initial record Magikarp being 1067mm, or 3'6". Note that this is longer than in other versions that used metric units (they initialized to 105.3mm in GSC and 106.5mm in HGSS), but preserving existing Polished balance will …

Magikarp length

---

utils/optimize.py

Produces the same output as before (including the order of the output; verified by a diff checker) when run against pret/pokecrystal and its ~5k matches, except it completes in 26.24 seconds instead of the original 73.84 seconds.

Faster optimize.py
