- battle/core.asm
- engine/move_mon.asm
> Fix some bugs

- battle/core.asm
- battle/effects/abilities.asm
This might fix the animation bug with weather animations, but I don't really understand what's going on.
Also fixes Hustle (previously it decreased accuracy by *50%* and for all moves, not just physical)
> Some bug fixes

- TODO.md
- battle/core.asm
- battle/effect_commands.asm
- battle/effects/abilities.asm
- battle/effects/thief.asm
- battle/moves/move_effects.asm
- engine/scripting.asm
- home/battle.asm
- main.asm
- text/battle.asm
- wram.asm
Improves Thief handling, retains consumable battle items (except for Berries) after battle, implements Pickup (in battle) and Harvest
> Change item usage handling

- TODO.md
- battle/effect_commands.asm
> Air Balloon should only give immunity to Ground, not everything

- TODO.md
- battle/core.asm
- battle/effect_commands.asm
- battle/effects/abilities.asm
- battle/effects/transform.asm
- utils/bank_ends.txt
See commit descriptions for more info. Notable inclusions: implement Binding Band, fix weather animations playing stray animations from old attacks/etc
> Bugfixes, new features and optimizations

- TODO.md
- battle/effect_command_pointers.asm
- battle/effect_commands.asm
- battle/effects/thief.asm
- battle/moves/move_effects.asm
- macros/move_effect.asm
- utils/bank_ends.txt
That marks the last unimplemented in-battle ability being implemented. There might be bugs lurking about in existing ones, though.
> Implement Pickpocket

- data/text/battle.asm
- engine/events/specials_2.asm
- Fixes typo in Perish Song text.
- Fixes "Masuda" Ditto's stats not being recalculated after setting its IVs and Nature.
> Fix two bugs

- maps/ElmsLab.asm
> Add Lyra facing Elm when talking to him (issue #275)

- .github/workflows/main.yml
Adds a build script that builds a "nightly" release on push to master. It automatically prunes the last release tagged as `nightly`.
> Add build script

- engine/pokemon/mon_menu.asm
This PR adds a swap entry to the party item menu, allowing to swap items held by two pokemons. 
Fix https://github.com/Rangi42/polishedcrystal/issues/534
> Swap Items

- data/phone/text/lyra.asm
- engine/phone/phone_scripts.asm
This PR is inspired by issue #652 (Make calling Lyra useful). If the player calls Lyra when Magneton is in the party, she wil tell you about it's evolution method.
I would like to further extend this for other Pokémon, but thought it was a good idea to first ask for any feedback here.
> First implementation of Lyra telling you about Pokémon evolution methods

- data/pokemon/dex_entries/012.asm
Bees make honey from flowers, but the flowers themselves only emit pollen which many bugs feast on.
> Correct the Butterfree dex entry

- INSTALL.md
See https://github.com/gbdev/rgbds/issues/862
> Update Mac OS X Install Docu

- engine/battle/core.asm
- macros/wram.asm
> Actually Fix the Link Battle Record

- engine/battle_anims/functions.asm
Does not change the sha1 of the rom.
Adds a table assert to the table and update some of the labels to match pret (and polished constants).
> Update `Dobattleanimframe`  w/ table assert & labels

- engine/menus/start_menu.asm
- engine/overworld/player_movement.asm
Restores `CheckTrainerRun` from prism.
> Restore `CheckTrainerRun` (Ported from Prism)

- charmap.asm
- data/text/ngrams.asm
- engine/menus/intro_menu.asm
- home/battle_vars.asm
- home/clear_sprites.asm
- home/init.asm
- home/text.asm
- home/vblank.asm
- ram/hram.asm
Mostly saving ROM0 space
Tables of offsets are slightly faster and could be applied more generally, but reducing footprint was the goal here
And speed bootup a bit, not much actual time saved but it is noticable
> Some more optimization

- engine/overworld/events.asm
- engine/overworld/scripting.asm
- engine/pokemon/move_mon.asm
- home/map.asm
- ram/hram.asm
- ram/wramx.asm
Saves a good chunk of rom
Though it is also faster most scripts seem short enough that the performance is largely irrelevant
> Script engine changes

- Makefile
- home/audio.asm
- home/copy.asm
- home/predef.asm
- home/print_text.asm
- home/text.asm
- home/vblank.asm
- ram/hram.asm
Either using the hTempBank alias where apropriate or refactoring out the need completely
hTempBank no longer needs to be preserved during vblank
Conflicts with #816 which i discovered needs more work
> Remove hBuffer

- utils/optimize.py
Allows passing an arbitrary set of files/folders
> Rewrite argument handling in optimize.py

- home/init.asm
- layout.link
267 ROM0 bytes practically for free
> Move bulk of the init code out of rom0

- engine/gfx/dynamic_pals.asm
- engine/link/link.asm
- utils/farcheck.py
Pretty sure this isn't what you meant by 'like farcheck.py' but it does have the advantage of no upkeep if rst symbols change
> Check for calls to rst functions in farcheck.py

- data/wild/treemons_asleep.asm
- engine/battle/core.asm
Sort of already did but indexed it with IsInByteArray
Generalized the table for all 4 daytimes as well
Might make sense to have a GetSpeciesAndFormForTempMon or similar
> Update CheckSleepingTreeMon to use a species/form table

- maps/EcruteakGym.asm
- maps/Route34.asm
- maps/VioletGym.asm
Likely introduced by 9b322012
This uses the warp event instead of hard coding warp coordinates
> Fix Violet gym guy throwing you across the street

- .github/workflows/build.yml
- .github/workflows/main.yml
- .github/workflows/nightly.yml
Seperates main.yml into build.yml and nightly.yml
This change allows build.yml to be called from Pull Requests, adding an additional check towards "completed" status so that an automated process can ensure that PRs will build after merge.
> Workflow overhaul

- maps/OaksLab.asm
Resolves Rangi42/polishedcrystal#879
> removed text from oak's lab trash can

- audio/engine.asm
PlaySFX clears channels before starting, PlayStereoSFX did not. This appears to be the cause of audio issues reported on discord, as prior to afb460ddc04377834c6e3432d77c44c5edf48e17 PlayStereoSFX would jump to PlaySFX if stereo was disabled
The two functions were essentially equivalent otherwise so merging them amounts to adding stereo masking to PlaySFX
PlayStereoSFX is used exclusively by BattleAnimCmd_Sound in `engine/battle_anims/anim_commands.asm`
> Merge PlaySFX and PlayStereoSFX

- engine/battle/effect_commands.asm
- engine/battle/stats.asm
Should work exactly like in the official games. Also fixed (?) some bugs (?) in the original code, not sure why they were like that but when I changed it, the abilities started working properly.
> Implement Mind's Eye as an actual ability.

- engine/gfx/fade.asm
Just because it's been bothering me. Sorry.
> update w(BG|OB)Pals variable names in comment

- maps/RuinsOfAlphAerodactylChamber.asm
- maps/RuinsOfAlphHoOhChamber.asm
- maps/RuinsOfAlphKabutoChamber.asm
- maps/RuinsOfAlphOmanyteChamber.asm
- maps/RuinsOfAlphSinjohChamber.asm
> Fix Player Sprite when bonking Alph tile description wall

- engine/overworld/wildmons.asm
> fix route 16 ghost encounter bug

- FAQ.md
Quick update to the FAQ on "How do I evolve my Pokemon?"
The former still had the instructions to call Lyra which is no longer the method; instead you now call Professor Elm.  Updated to reflect this change.
> FAQ Update

- data/moves/moves.asm
> fix final "no-accuracy" moves

- engine/battle/ai/scoring.asm
- engine/battle/core.asm
- engine/battle_anims/anim_commands.asm
- home/battle.asm
Edited to fix several bugs.
Tracking this down took a couple hours. No clue why this was changed. Either way, it causes stuff like battle hud not disappearing during attacks, attack based palette changes to persist, and the game would randomly crash when starting a battle. If this is intentional... let me know I suppose lol.
[Original commit](https://github.com/Rangi42/polishedcrystal/commit/83d3752b5c18d9a107c49706b7c93b950c871c0e#diff-a6d98e72dba8f77bc26099eded3633a92fba68e510b187e492d932b12149a846L53)
* Move priority comparison swapped high and low bytes
* A fix for the summary screen category rendering broke in battle move categories
* Found a random potential deadlock in ai code, not actually sure if this is 10bit specific...
> [10bit] Fix various bugs

- data/moves/animations.asm
- engine/battle_anims/anim_commands.asm
- macros/scripts/battle_anims.asm
This also optimizes several existing animations
> Add several new Battle Animation Commands
